### PR TITLE
fix things

### PR DESCRIPTION
**Pull request by kot83**

### CODE REVIEW

**Comment by kot83** [comment]
fuck this was abandonware anyway

**Comment by ohlookitsAugust** [comment]
same xd:tm:

**Comment by ry0id** [comment]
kot

**Comment by ry0id** [comment]
what is this

**Comment by ReKTDevlol** [comment]
amjust 2 lazy and was 2 tired :^)

**Comment by kot83** [comment]
no u

**Comment by ry0id** [comment]
i'll leave this to rekt, i don't maintain this repository

**Comment by ry0id** [comment]
reopen if needed @ReKTDevlol

**Pull request closed without merging**
